name: Test Deploy

on:
  push:
    branches:
      - "*"
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  call-workflow:
    uses: ekaterinayefimovich/terraform-oidc/.github/workflows/terraform-plan-pipeline.yml@main
    with:
      environment_name: infrastructure
